export const ArticlesData = [
  {
    id: "1",
    title: "1: The Art of Autumn",
    author: "Jane Doe",
    date: "2021-10-05",
    content: "Detailed content about autumn...",
    authorImageUrl: "url-to-author-image.jpg",
    authorBio: "Author biography here...",
    hashtags: [{ tag: "#autumn", url: "/tags/autumn" }],
    relatedArticles: [{ tag: "Winter Winds", url: "/article/2" }],
  },
  {
    id: "2",
    title: "2: The Art of Autumn",
    author: "Jane Doe",
    date: "2021-10-05",
    content: "Detailed content about autumn...",
    authorImageUrl: "url-to-author-image.jpg",
    authorBio: "Author biography here...",
    hashtags: [{ tag: "#autumn", url: "/tags/autumn" }],
    relatedArticles: [{ tag: "Winter Winds", url: "/article/2" }],
  },
  {
    id: "3",
    title: "3: The Art of Autumn",
    author: "Jane Doe",
    date: "2021-10-05",
    content: "Detailed content about autumn...",
    authorImageUrl: "url-to-author-image.jpg",
    authorBio: "Author biography here...",
    hashtags: [{ tag: "#autumn", url: "/tags/autumn" }],
    relatedArticles: [{ tag: "Winter Winds", url: "/article/2" }],
  },
  {
    id: "4",
    title: "4: The Art of Autumn",
    author: "Jane Doe",
    date: "2021-10-05",
    content: "Detailed content about autumn...",
    authorImageUrl: "url-to-author-image.jpg",
    authorBio: "Author biography here...",
    hashtags: [{ tag: "#autumn", url: "/tags/autumn" }],
    relatedArticles: [{ tag: "Winter Winds", url: "/article/2" }],
  },
];
export default ArticlesData;
